name: ActionBuild

on:
  push:
    branches: [ master, develop ]

jobs:
    ActionBuild:
        runs-on: macos-latest
        strategy:
            matrix:
                run-config:
                    - { scheme: 'BullsEye',   configuration: 'Debug', project: 'BullsEye.xcodeproj', build: 1, analyze: 0, test: 0, info: 1, destination: 'generic/platform=iOS Simulator,name=iPhone 12' }
        steps:
            - uses: actions/checkout@v1
            - uses: macmade/action-xcodebuild@v1.0.0