name: Build Action

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: macos-10.15
    timeout-minutes: 15
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Select Xcode 12"
        uses: st3fan/xcode-select@main
        with:
            version: "12"

      - name: Run tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
            project: BullsEye.xcodeproj
            scheme: BullsEye
            derived-data-path: ./output
            destination: "OS=14.4,name=iPhone 12 Pro"
            action: test
            enable-code-coverage: true

      - name: Test Coverage
        uses: maxep/xcodebuild-lcov-action@0.1.0
        with:
            derived-data-path: ./output
            target: BullsEye.app
            output-file: ./output/lcov.info